version: '3'
services:
  postgres-db:
    image: postgres:15
    container_name: apartments-system-db
    environment:
      POSTGRES_DB: nawy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "nawy"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    container_name: apartments-system-backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      PORT: 3000
      DATABASE_URL: "postgresql://user:pass@postgres-db:5432/nawy"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    container_name: apartments-system-frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
      - /app/.next
    ports:
      - "4000:4000"
    depends_on:
      backend:
        condition: service_healthy
  
volumes:
  pgdata:
